version: "3.3"

networks:
  jenkins:
    external:
      name: jenkins

services:

  jenkins:
    image: $JENKINS_REPO
    container_name: jenkins
    hostname: jenkins
    volumes:
      - "/var/jenkins/jenkins_home:/var/jenkins_home"
      - "/var/jenkins/data:/data"
    networks:
      - jenkins
    ports:
      "${JENKINS_PORT}:8080"
    logging:
      driver: journald
